function [omega,r,s] = ComputeOmegaKozhevnikov(n_single_column, kr, E, fComputePhotoSource, Const_Omega)
% ComputeOmegaKozhevnikov - Auto-generated function
% This function is automatically generated by another MATLAB function.
persistent Sph
% Initialize the output
n = reshape(n_single_column,[],9);
omega = zeros(size(n));

% Naming the species
n_e = n(:,1);
n_N2 = n(:,2);
n_O2 = n(:,3);
n_N2p = n(:,4);
n_O2p = n(:,5);
n_O2m = n(:,6);
n_O = n(:,7);
n_N = n(:,8);
n_O4p = n(:,9);

% Reactions
r(:,1) = kr(:,1) .* n_e.* n_N2;
r(:,2) = kr(:,2) .* n_e.* n_O2;
r(:,3) = kr(:,3) .* n_e.* n_O2p.* n_e;
r(:,4) = kr(:,4) .* n_O2.* n_N2p;
r(:,5) = kr(:,5) .* n_e.* n_N2.* n_N2p;
r(:,6) = kr(:,6) .* n_e.* n_O2.* n_N2p;
r(:,7) = kr(:,7) .* n_e.* n_N2.* n_O2p;
r(:,8) = kr(:,8) .* n_e.* n_O2.* n_O2p;
r(:,9) = kr(:,9) .* n_e.* n_O4p;
r(:,10) = kr(:,10) .* n_e.* n_O2p;
r(:,11) = kr(:,11) .* n_e.* n_N2p;
r(:,12) = kr(:,12) .* n_e.* n_O2.* n_O2;
r(:,13) = kr(:,13) .* n_O2.* n_O2m;
r(:,14) = kr(:,14) .* n_e.* n_N2.* n_O2;
r(:,15) = kr(:,15) .* n_N2.* n_O2m;
r(:,16) = kr(:,16) .* n_e.* n_O2.* n_O;
r(:,17) = kr(:,17) .* n_N2.* n_O2.* n_O2p;
r(:,18) = kr(:,18) .* n_O2.* n_O2p.* n_O2;
r(:,19) = kr(:,19) .* n_O2.* n_O4p;
r(:,20) = kr(:,20) .* n_e.* n_N2;
r(:,21) = kr(:,21) .* n_e.* n_O2;
r(:,22) = kr(:,22) .* n_O2m.* n_O4p;
r(:,23) = kr(:,23) .* n_N2.* n_O2m.* n_O4p;
r(:,24) = kr(:,24) .* n_O2.* n_O2m.* n_O4p;
r(:,25) = kr(:,25) .* n_N2.* n_O2p.* n_O2m;
r(:,26) = kr(:,26) .* n_O2.* n_O2p.* n_O2m;

s = r(:,1) + r(:,2);
if isempty(Sph)
    Sph = fComputePhotoSource(E,s);
end

% Omega
omega(:,1) = +1*r(:,1)+1*r(:,2)-1*r(:,3)-1*r(:,5)-1*r(:,6)-1*r(:,7)-1*r(:,8)-1*r(:,9)-1*r(:,10)-1*r(:,11)-1*r(:,12)+1*r(:,13)-1*r(:,14)+1*r(:,15)-1*r(:,16) + Sph + Const_Omega;
omega(:,2) = -1*r(:,1)+1*r(:,4)+1*r(:,5)+1*r(:,6)-1*r(:,20);
omega(:,3) = -1*r(:,2)+1*r(:,3)-1*r(:,4)+1*r(:,7)+1*r(:,8)+2*r(:,9)-1*r(:,12)+1*r(:,13)-1*r(:,14)+1*r(:,15)-1*r(:,16)-1*r(:,17)-1*r(:,18)+1*r(:,19)-1*r(:,21)+3*r(:,22)+3*r(:,23)+3*r(:,24)+2*r(:,25)+2*r(:,26);
omega(:,4) = +1*r(:,1)-1*r(:,4)-1*r(:,5)-1*r(:,6)-1*r(:,11) + 1e13 + Sph*0.33 + Const_Omega*0.33;
omega(:,5) = +1*r(:,2)-1*r(:,3)+1*r(:,4)-1*r(:,7)-1*r(:,8)-1*r(:,10)-1*r(:,17)-1*r(:,18)+1*r(:,19)-1*r(:,25)-1*r(:,26) + Sph*0.33 + Const_Omega*0.33;
omega(:,6) = +1*r(:,12)-1*r(:,13)+1*r(:,14)-1*r(:,15)+1*r(:,16)-1*r(:,22)-1*r(:,23)-1*r(:,24)-1*r(:,25)-1*r(:,26);
omega(:,7) = +2*r(:,10)+2*r(:,21);
omega(:,8) = +2*r(:,11)+2*r(:,20);
omega(:,9) = -1*r(:,9)+1*r(:,17)+1*r(:,18)-1*r(:,19)-1*r(:,22)-1*r(:,23)-1*r(:,24) + Sph*0.33 + Const_Omega*0.33;

end

